[theme]
primaryColor = "#4dabf7"  # Soft sky blue
backgroundColor = "#f7f9fb"  # Very light grey/blue background
secondaryBackgroundColor = "#e0e4ec"  # Light secondary grey
textColor = "#1f1f1f"  # Dark soft grey for text
font = "sans serif"